version: '3'

services:
  vue:
    build:
      context: .
      dockerfile: vue.Dockerfile
    volumes:
      - ./vue-axios:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    command: npm run serve
    container_name: vue
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php
    volumes:
      - ./php-laravel/:/var/www/html/
    ports:
      - 8000:80
  mysql:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: minhasenha123
      MYSQL_DATABASE: meubd
      MYSQL_USER: meuuser
      MYSQL_PASSWORD: minhasenha
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports: 
      - "3307:3306"
  

  
 
  
